x-paddler-common: &paddler-common
  image: paddler:v4.0.1
  build: ..
  network_mode: host

services:
  paddler-balancer:
    <<: *paddler-common
    container_name: paddler-balancer
    command: [
      "balancer",
      "--management-addr", "127.0.0.1:8060",
      "--inference-addr", "127.0.0.1:8061",
      "--web-admin-panel-addr", "127.0.0.1:8062"
    ]

  paddler-agent1:
    <<: *paddler-common
    container_name: paddler-agent1
    depends_on:
      - paddler-balancer
    command: [
      "agent",
      "--name", "llm-1",
      "--management-addr", "127.0.0.1:8060"
    ]

  paddler-agent2:
    <<: *paddler-common
    container_name: paddler-agent2
    depends_on:
      - paddler-balancer
    command: [
      "agent",
      "--name", "llm-2",
      "--management-addr", "127.0.0.1:8060"
    ]

volumes:
  hf-cache:
