[package]
name = "paddler_service_thread"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Runs a bundle of Paddler services on a dedicated thread until it is cancelled"
homepage.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
actix-web = { workspace = true }
anyhow = { workspace = true }
log = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
trzcina = { workspace = true }

[dev-dependencies]
async-trait = { workspace = true }

[lints]
workspace = true
