[package]
name = "paddler_cli"
autotests = false
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "CLI binary for Paddler"
homepage.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "paddler"
path = "src/main.rs"

[[test]]
name = "integration"
path = "tests/main.rs"

[dependencies]
actix-web = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
clap = { workspace = true }
command_handler = { workspace = true }
env_logger = { workspace = true }
paddler_agent_runner = { workspace = true }
paddler_balancer = { workspace = true }
paddler_balancer_runner = { workspace = true }
paddler_service_thread = { workspace = true }
paddler_state_database = { workspace = true }
tokio-util = { workspace = true }
trzcina = { workspace = true }

[lints]
workspace = true

[features]
default = []
cuda = ["paddler_agent_runner/cuda"]
metal = ["paddler_agent_runner/metal"]
vulkan = ["paddler_agent_runner/vulkan"]
web_admin_panel = [
    "paddler_balancer/web_admin_panel",
    "paddler_balancer_runner/web_admin_panel",
]
