[package]
name = "paddler_request_registry"
authors.workspace = true
description.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
dashmap = { workspace = true }
tokio = { workspace = true }

[lints]
workspace = true
