name: docker

on:
  pull_request:
    branches:
      - "**"
    types:
      - edited
      - opened
      - ready_for_review
      - review_requested
      - synchronize
  push:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: build the image
        run: make docker.image
