mod balancer_distributes_buffered_requests_across_two_agents;
mod balancer_distributes_embedding_batch_across_agents;
mod balancer_distributes_embedding_batch_across_agents_with_uneven_slots;
mod balancer_distributes_embedding_burst_evenly_across_agents;
mod balancer_distributes_token_burst_evenly_across_agents;
mod balancer_emits_overflow_errors_when_embedding_burst_exceeds_max_buffered_requests;
mod balancer_fans_out_embedding_batch_to_all_agents;
mod balancer_registers_multiple_agents_over_time;
#[cfg(feature = "web_admin_panel")]
mod balancer_serves_every_service_within_the_default_macos_open_file_limit;
mod balancer_serves_on_the_addresses_it_announces;
#[cfg(feature = "web_admin_panel")]
mod balancer_web_admin_panel_shows_its_command_line_configuration;
mod balancer_without_compatibility_flags_serves_no_compatibility_services;
mod management_metrics_endpoint_sums_the_slots_of_registered_agents;
