mod balancer_distributes_buffered_requests_across_two_agents;
mod balancer_distributes_embedding_batch_across_agents;
mod balancer_distributes_embedding_batch_across_agents_with_uneven_slots;
mod balancer_distributes_embedding_burst_evenly_across_agents;
mod balancer_distributes_token_burst_evenly_across_agents;
mod balancer_emits_overflow_errors_when_embedding_burst_exceeds_max_buffered_requests;
mod balancer_fans_out_embedding_batch_to_all_agents;
mod balancer_registers_multiple_agents_over_time;
