mod agent_reconnects_to_its_balancer_after_the_balancer_restarts;
mod balancer_answers_gateway_timeout_when_a_paused_agent_never_answers;
mod balancer_distributes_buffered_requests_across_two_agents;
mod balancer_distributes_embedding_batch_across_agents;
mod balancer_distributes_embedding_batch_across_agents_with_uneven_slots;
mod balancer_distributes_embedding_burst_evenly_across_agents;
mod balancer_distributes_token_burst_evenly_across_agents;
mod balancer_emits_overflow_errors_when_embedding_burst_exceeds_max_buffered_requests;
mod balancer_fans_out_embedding_batch_to_all_agents;
mod balancer_inference_cors_flag_allows_its_origin;
mod balancer_keeps_an_agent_connected_after_it_answers_a_request_that_timed_out;
mod balancer_management_cors_flag_allows_its_origin;
mod balancer_registers_multiple_agents_over_time;
#[cfg(feature = "web_admin_panel")]
mod balancer_serves_every_service_within_the_default_macos_open_file_limit;
mod balancer_serves_on_the_addresses_it_announces;
#[cfg(feature = "web_admin_panel")]
mod balancer_web_admin_panel_shows_its_command_line_configuration;
mod balancer_without_compatibility_flags_serves_no_compatibility_services;
mod http_client_reports_a_balancer_killed_before_responding_as_a_failed_request;
mod inference_socket_connection_drops_pending_requests_when_the_balancer_is_killed;
mod management_metrics_endpoint_sums_the_slots_of_registered_agents;
mod openai_chat_completion_reports_an_agent_killed_mid_generation_as_a_bad_gateway;
mod subprocess_signals_refuse_a_child_that_was_already_reaped;
mod subprocess_signals_report_a_killed_process_that_cannot_be_paused;
mod subprocess_signals_report_a_reaped_process_that_cannot_be_signalled;
mod typesafe_system_one_reports_an_agent_killed_mid_decision_as_a_bad_gateway;
